name: Auto Firmware Dumper

on:
  workflow_dispatch:
    inputs:
      USER_NAME:
        description: 'Name of your GitHub Account'
        required: true
        default: 'ajugeorge98'
      USER_EMAIL:
        description: 'E-mail of your GitHub Account'
        required: true
        default: 'ajimsjames.gvilla@gmail.com'
      FIRMWARE_URL:
        description: 'Stock ROM Link'
        required: true
        default: 'https://mirrors.lolinet.com/firmware/lenomola/2024/tank/official/TELEU/XT2407-1_TANK_TELEU_15_V1UWS35H.63-14-6-4-2-4_subsidy-DEFAULT_regulatory-DEFAULT_cid50_CFC.xml.zip'
      GENERATE_VENDOR:
        description: 'Create Vendor Tree'
        required: true
        default: 'false'
        type: boolean
      UPLOAD_LINEAGE_DT:
        description: 'Upload LineageOS tree'
        required: true
        default: 'false'
        type: boolean
      UPLOAD_TWRP_DT:
        description: 'Upload TWRP tree'
        required: true
        default: 'false'
        type: boolean

jobs:
  dump:
    name: Auto Firmware Dumper
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GTOKEN }}
      TWT: ${{ github.event.inputs.UPLOAD_TWRP_DT }}
      LOT: ${{ github.event.inputs.UPLOAD_LINEAGE_DT }}
      GVT: ${{ github.event.inputs.GENERATE_VENDOR }}
      FUR: ${{ github.event.inputs.FIRMWARE_URL }}
      UN: ${{ github.event.inputs.USER_NAME }}
      UEM: ${{ github.event.inputs.USER_EMAIL }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: rokibhasansagar/slimhub_actions@main
      - uses: sersoft-gmbh/setup-gh-cli-action@v2
        with:
          version: stable

      - name: Setting Up Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip lz4 axel p7zip-full
          pip install uv
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          sudo chmod -R 755 *
          mkdir -p workdir
          bash scripts/full_setup.sh "$PWD/workdir"
        working-directory: ${{ github.workspace }}

      - name: Authorize Git And GitHub CLI
        run: |
          . scripts/common_functions.sh
          git_auth "${{ env.UN }}" "${{ env.UEM }}" "${{ env.GITHUB_TOKEN }}"
        working-directory: ${{ github.workspace }}

      - name: Create Dump
        run: |
          cd workdir/DumprX
          bash dumper.sh "${{ env.FUR }}"
          sudo chown -R $USER:$USER out
          chmod -R 755 out
        working-directory: ${{ github.workspace }}

      - name: Upload ROM Dump
        run: |
          . scripts/common_functions.sh
          BASE_DIR="${{ github.workspace }}"
          DUMP_DIR="$BASE_DIR/workdir/DumprX"
          DUMP_OUT_DIR="$DUMP_DIR/out"

          cd "$DUMP_DIR"
          dump_props_to_env_file "$DUMP_OUT_DIR"
          
          if [ -f "env" ]; then
            mv env "$BASE_DIR/env"
          else
            echo "::error::env file not generated."
            exit 1
          fi

          cd "$BASE_DIR"
          . env
          
          if [ -d "$DUMP_OUT_DIR" ]; then
            cd "$DUMP_OUT_DIR"
          else
            echo "::error::Directory $DUMP_OUT_DIR not found!"
            exit 1
          fi

          lineageDir="lineage-device-tree"
          teamWinDir="twrp-device-tree"
          
          [ -d "$lineageDir" ] && cp -r "$lineageDir" "$BASE_DIR/" || echo "Lineage tree not found."
          [ -d "$teamWinDir" ] && cp -r "$teamWinDir" "$BASE_DIR/" || echo "TWRP tree not found."
          
          compress_files "$PWD"
          bash "$BASE_DIR/scripts/upload_to_repo.sh" "$PWD" dump
        working-directory: ${{ github.workspace }}

      - name: Create And Upload Vendor Tree
        if: env.GVT == 'true'
        run: |
          . scripts/common_functions.sh
          [ -f env ] && . env
          BASE_DIR="${{ github.workspace }}"
          cd "$BASE_DIR/workdir"
          
          lineageDir="$BASE_DIR/lineage-device-tree"
          TARGET_DIR="android/device/$BRAND/$DEVICE"
          
          if [ -d "$lineageDir" ]; then 
            mkdir -p "$TARGET_DIR"
            cp -r $lineageDir/* "$TARGET_DIR/"
          else 
            echo "::error::Cannot find Lineage device tree!"
            exit 1
          fi
          
          cd "$TARGET_DIR" && chmod 755 *.sh
          bash extract-files.sh "$BASE_DIR/workdir/DumprX/out"
          
          cd "../../vendor/$BRAND/$DEVICE"
          chmod -R 755 *
          bash "$BASE_DIR/scripts/upload_to_repo.sh" "$PWD" vendor
        working-directory: ${{ github.workspace }}

      - name: Upload LineageOS Device Tree
        if: env.LOT == 'true'
        run: |
          [ -f env ] && . env
          bash "${{ github.workspace }}/scripts/upload_to_repo.sh" "${{ github.workspace }}/lineage-device-tree" lineage lineage_device
        working-directory: ${{ github.workspace }}
        continue-on-error: true

      - name: Upload TWRP Device Tree
        if: env.TWT == 'true'
        run: |
          [ -f env ] && . env
          RECOVERY_PATH=$(find twrp-device-tree -name "$CODENAME" -type d | head -n 1)
          if [ -n "$RECOVERY_PATH" ]; then
            bash "${{ github.workspace }}/scripts/upload_to_repo.sh" "$RECOVERY_PATH" twrp recovery_device
          else
            echo "TWRP tree not found."
          fi
        working-directory: ${{ github.workspace }}
        continue-on-error: true
